[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning to ignore false positives
[build.processing]
  skip_processing = false

# Ignore common false positive patterns
[[plugins]]
  package = "@netlify/plugin-secrets-scanning"
  
  [plugins.inputs]
    # Skip scanning these file patterns
    omit_paths = [
      "*.md",
      "*.json", 
      "*.lock",
      "*.lockb",
      "*.sql",
      "dist/**/*",
      "node_modules/**/*",
      ".netlify/**/*",
      "SETUP_GUIDE.md",
      "MVP_SETUP_GUIDE.md",
      "IMPLEMENTATION_COMPLETE.md",
      "USAGE.md"
    ]
    
    # Skip these specific keys that are just variable names
    omit_keys = [
      "VITE_APP_NAME",
      "VITE_APP_VERSION", 
      "VITE_ELEVENLABS_VOICE_ID"
    ]

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PWA manifest and service worker
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0"
